### PR TITLE
217 holding pages

### PR DESCRIPTION
**Pull request by EdwardAndress**
https://dsdmoj.atlassian.net/browse/CT-88

### CODE REVIEW

**Comment by misaka** [comment]
I was going to comment that we're duplicating images by adding them with this commit, but it looks like these images aren't already a part of the project ... they're being pulled in with a gem. :)

**Comment by misaka** [comment]
How about an addition to the README about how the `500-nginx.html` file is used?

**Comment by EdwardAndress** [comment]
How about I put a comment at the top of the file instead?

**Comment by misaka** [comment]
@EdwardAndress I just think that I'd expect to see the instructions for use in the README ...  I wouldn't think to look for the HTML file when setting this application up. Also, if it's a comment in the HTML file it'll be delivered to whoever gets a 500 error (invisible in the source). Not sure we'd want that. ;)

**Comment by EdwardAndress** [comment]
I just can't quite get my head around the use case for this info, which means I can't quite work out how to write it or what to write.

**Comment by misaka** [comment]
Imagine someone is setting up this project for the first time. For example, there is a catastrophic event and we lose the systems we have in AWS and have to set things up from scratch in a hurry. Or maybe we want to migrate to a new cloud platform and we want to setup the correspondence tool there. What we would want is instructions on how to get this app up and running for the first time in a production environment ... and sure, there's a ton of info to go there. Redis, SideKiq, etc, but we need to start somewhere. Also, since we know that this event is unlikely and we don't know specifics we shouldn't go into great detail (for example, how do we know we'll even be running NGinx, we could be migrating to Apache or a service-based web-serving architecture). It'd probably be enough to have something like:

```
== Production Environment Setup

=== Web Server Setup

`public/500-nginx.html` provides a static 500 error for when the Rails application cannot be reached.
```

Should probably also mention the CSS and images.

**Comment by EdwardAndress** [comment]
OK.  Agreed.  We should add another ticket into the backlog for inserting the other details that would be helpful in the scenario you describe.

**Pull request merged**
